package entities

import (
	"strings"
)

// ValidateSHA512256 validates that a given value is a valid SHA512-256 hash.
// It takes an interface{} value and returns the validated hash as a string,
// the hash generated by the GenerateSHA3256 function, and an error if any.
func ValidateSHA512256(value string) (string, string, error) {
	v := strings.ToLower(value)
	e := ValidateRegEx(`^[0-9a-f]{64}$`, v)
	if e != nil {
		return "", "", e
	}

	return v, GenerateSHA3256(v), nil
}
