package plugins

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/assert"
)

type Address struct {
	Street *string `json:"street"`
	City   *string `json:"city"`
	Zip    *string `json:"zip"`
}

type Contact struct {
	Type  *string `json:"type"`
	Value *string `json:"value"`
}

type TestData struct {
	Name     *string        `json:"name"`
	Age      *int           `json:"age"`
	Score    *float64       `json:"score"`
	Address  *Address       `json:"address"`
	Contacts []*Contact     `json:"contacts"`
	Metadata map[string]any `json:"metadata"`
	Tags     []string       `json:"tags"`
	IP       *string        `json:"ip"`
}

var cCache = new(CELCache)

func TestEvaluate(t *testing.T) {
	name := "Alice"
	age := 30
	score := 90.5

	// Address fields
	street := "123 Main St"
	city := "New York"
	zip := "10001"

	// Contact fields
	emailType := "email"
	emailValue := "alice@example.com"
	phoneType := "phone"
	phoneValue := "555-123-4567"
	ipAddr := "192.168.0.1"

	// Tags
	tags := []string{"student", "premium", "active"}

	// Create complete test data with nested structures
	completeData := &TestData{
		Name:  &name,
		Age:   &age,
		Score: &score,
		Address: &Address{
			Street: &street,
			City:   &city,
			Zip:    &zip,
		},
		Contacts: []*Contact{
			{
				Type:  &emailType,
				Value: &emailValue,
			},
			{
				Type:  &phoneType,
				Value: &phoneValue,
			},
		},
		Metadata: map[string]any{
			"isActive":    true,
			"yearJoined":  2020,
			"avgGrade":    85.5,
			"department":  "Computer Science",
			"preferences": map[string]any{"theme": "dark", "notifications": true},
			"nullValue":   nil,
			"emptyMap":    map[string]any{},
			"mapWithNil":  map[string]any{"key": nil},
		},
		Tags: tags,
		IP:   &ipAddr,
	}

	// Create data with nil fields for testing nil handling
	var nilStreet, nilCity, nilZip *string
	var nilEmailType, nilEmailValue *string

	dataWithNils := &TestData{
		Name:  &name,
		Age:   &age,
		Score: nil,
		Address: &Address{
			Street: nilStreet,
			City:   nilCity,
			Zip:    nilZip,
		},
		Contacts: []*Contact{
			{
				Type:  nilEmailType,
				Value: nilEmailValue,
			},
			nil,
		},
		Metadata: map[string]any{
			"hasNilValues": true,
			"nilMap":       nil,
		},
		Tags: []string{},
	}

	tests := []struct {
		name       string
		data       *TestData
		expression string
		want       bool
		expectErr  bool
	}{
		{
			name: "valid expression true",
			data: &TestData{
				Name:  &name,
				Age:   &age,
				Score: &score,
			},
			expression: "age > double(20)",
			want:       true,
			expectErr:  false,
		},
		{
			name: "valid expression false",
			data: &TestData{
				Name:  &name,
				Age:   &age,
				Score: &score,
			},
			expression: "age < double(20)",
			want:       false,
			expectErr:  false,
		},
		{
			name: "complex expression true",
			data: &TestData{
				Name:  &name,
				Age:   &age,
				Score: &score,
			},
			expression: `age > double(20) && score > 85.0`,
			want:       true,
			expectErr:  false,
		},
		{
			name: "complex expression false",
			data: &TestData{
				Name:  &name,
				Age:   &age,
				Score: &score,
			},
			expression: `age > double(40) || score < 50.0`,
			want:       false,
			expectErr:  false,
		},
		{
			name: "missing field in expression",
			data: &TestData{
				Name: &name,
				Age:  &age,
			},
			expression: `score > 80.0`,
			want:       false,
			expectErr:  true,
		},
		{
			name: "invalid expression syntax",
			data: &TestData{
				Name:  &name,
				Age:   &age,
				Score: &score,
			},
			expression: `age > `,
			want:       false,
			expectErr:  true,
		},
		{
			name:       "empty data",
			data:       nil,
			expression: `age > 30`,
			want:       false,
			expectErr:  true,
		},
		{
			name: "empty expression",
			data: &TestData{
				Name:  &name,
				Age:   &age,
				Score: &score,
			},
			expression: ``,
			want:       false,
			expectErr:  true,
		},
		{
			name:       "map value access",
			data:       completeData,
			expression: `metadata.isActive == true`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "nested map value access",
			data:       completeData,
			expression: `metadata.preferences.theme == "dark"`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "numeric comparison in map",
			data:       completeData,
			expression: `metadata.yearJoined >= 2020 && metadata.avgGrade > 80.0`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "array length check",
			data:       completeData,
			expression: `size(contacts) == 2`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "check value in array",
			data:       completeData,
			expression: `"premium" in tags`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "string operations",
			data:       completeData,
			expression: `startsWith("name", "Al") && endsWith("name", "ce") && contains("name", "lic")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "map key existence check",
			data:       completeData,
			expression: `"isActive" in metadata && !("nonExistent" in metadata)`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "multiple array elements check",
			data:       completeData,
			expression: `"student" in tags && "premium" in tags && "active" in tags && !("inactive" in tags)`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "complex nested map access",
			data:       completeData,
			expression: `metadata.preferences.theme == "dark" && metadata.preferences.notifications == true`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "string concatenation and comparison",
			data:       completeData,
			expression: `(name + " Smith") == "Alice Smith"`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "nil value in map",
			data:       completeData,
			expression: `metadata.nullValue == null`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "empty map in map",
			data:       completeData,
			expression: `size(metadata.emptyMap) == 0`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "nil value in nested map",
			data:       completeData,
			expression: `metadata.mapWithNil.key == null`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "empty array check",
			data:       dataWithNils,
			expression: `size(tags) == 0`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "nil value in map with condition",
			data:       dataWithNils,
			expression: `metadata.hasNilValues == true && metadata.nilMap == null`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "array size check",
			data:       completeData,
			expression: `size(contacts) == 2 && size(tags) == 3`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "array element presence check",
			data:       completeData,
			expression: `"student" in tags && "premium" in tags && "active" in tags`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "array element absence check",
			data:       completeData,
			expression: `!("nonexistent" in tags)`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "combined array and map operations",
			data:       completeData,
			expression: `size(contacts) == 2 && metadata.yearJoined > 2019 && "premium" in tags`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "inCIDR true",
			data:       completeData,
			want:       true,
			expression: `inCIDR("ip", "192.168.0.0/24")`,
			expectErr:  false,
		},
		{
			name:       "equals - field equals literal string",
			data:       completeData,
			expression: `equals("name", "Alice")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equals - field not equals literal string",
			data:       completeData,
			expression: `equals("address.city", "Los Angeles")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "equals - comparing metadata string values",
			data:       completeData,
			expression: `equals("metadata.department", "Computer Science")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equals - one field doesn't exist returns false",
			data:       completeData,
			expression: `equals("nonexistent.field", "name")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "equals - type mismatch number vs string returns false",
			data:       completeData,
			expression: `equals("age", "name")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "equals - type mismatch boolean vs string returns false",
			data:       completeData,
			expression: `equals("metadata.isActive", "name")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "equals - different string values",
			data:       completeData,
			expression: `equals("name", "address.city")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "equals - complex expression with AND",
			data:       completeData,
			expression: `equals("address.city", "New York") && equals("address.zip", "10001")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equals - complex expression with OR",
			data:       completeData,
			expression: `equals("address.city", "Boston") || equals("address.city", "New York")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equals - combined with exists",
			data:       completeData,
			expression: `exists("address.city") && equals("address.city", "New York")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equals - numeric strings comparison",
			data:       completeData,
			expression: `equals("address.zip", "10001")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equals - comparing street with literal",
			data:       completeData,
			expression: `equals("address.street", "123 Main St")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equals - comparing contact types",
			data:       completeData,
			expression: `equals("contacts.0.type", "email")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equals - array type returns false",
			data:       completeData,
			expression: `equals("tags", "tags")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "equals - integer value matches",
			data:       completeData,
			expression: `equals("age", 30)`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equals - float value matches",
			data:       completeData,
			expression: `equals("score", 90.5)`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - exact match same case",
			data:       completeData,
			expression: `equalsIgnoreCase("name", "Alice")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - match different case lowercase",
			data:       completeData,
			expression: `equalsIgnoreCase("name", "alice")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - match different case uppercase",
			data:       completeData,
			expression: `equalsIgnoreCase("name", "ALICE")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - match different case mixed",
			data:       completeData,
			expression: `equalsIgnoreCase("name", "aLiCe")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - no match different values",
			data:       completeData,
			expression: `equalsIgnoreCase("name", "Bob")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - city match case insensitive",
			data:       completeData,
			expression: `equalsIgnoreCase("address.city", "new york")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - city match uppercase",
			data:       completeData,
			expression: `equalsIgnoreCase("address.city", "NEW YORK")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - department match case insensitive",
			data:       completeData,
			expression: `equalsIgnoreCase("metadata.department", "computer science")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - department match uppercase",
			data:       completeData,
			expression: `equalsIgnoreCase("metadata.department", "COMPUTER SCIENCE")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - field doesn't exist returns false",
			data:       completeData,
			expression: `equalsIgnoreCase("nonexistent.field", "value")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - type mismatch number vs string returns false",
			data:       completeData,
			expression: `equalsIgnoreCase("age", "30")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - type mismatch boolean vs string returns false",
			data:       completeData,
			expression: `equalsIgnoreCase("metadata.isActive", "true")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - complex expression with AND",
			data:       completeData,
			expression: `equalsIgnoreCase("address.city", "NEW YORK") && equalsIgnoreCase("name", "alice")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - complex expression with OR",
			data:       completeData,
			expression: `equalsIgnoreCase("address.city", "BOSTON") || equalsIgnoreCase("address.city", "new york")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - combined with equals",
			data:       completeData,
			expression: `equals("address.zip", "10001") && equalsIgnoreCase("address.city", "NEW YORK")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - email case insensitive",
			data:       completeData,
			expression: `equalsIgnoreCase("contacts.0.value", "ALICE@EXAMPLE.COM")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - street address mixed case",
			data:       completeData,
			expression: `equalsIgnoreCase("address.street", "123 main st")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - contact type case insensitive",
			data:       completeData,
			expression: `equalsIgnoreCase("contacts.0.type", "EMAIL")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "equalsIgnoreCase - combined with exists",
			data:       completeData,
			expression: `exists("name") && equalsIgnoreCase("name", "ALICE")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "contains - field contains substring",
			data:       completeData,
			expression: `contains("name", "lic")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "contains - field contains full string",
			data:       completeData,
			expression: `contains("name", "Alice")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "contains - field does not contain substring",
			data:       completeData,
			expression: `contains("name", "Bob")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "contains - city contains substring",
			data:       completeData,
			expression: `contains("address.city", "York")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "contains - city contains prefix",
			data:       completeData,
			expression: `contains("address.city", "New")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "contains - street contains number",
			data:       completeData,
			expression: `contains("address.street", "123")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "contains - street contains word",
			data:       completeData,
			expression: `contains("address.street", "Main")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "contains - email contains domain",
			data:       completeData,
			expression: `contains("contacts.0.value", "@example.com")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "contains - email contains username",
			data:       completeData,
			expression: `contains("contacts.0.value", "alice")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "contains - department contains word",
			data:       completeData,
			expression: `contains("metadata.department", "Computer")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "contains - department contains partial word",
			data:       completeData,
			expression: `contains("metadata.department", "Science")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "contains - field doesn't exist returns false",
			data:       completeData,
			expression: `contains("nonexistent.field", "value")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "contains - type mismatch number vs string returns false",
			data:       completeData,
			expression: `contains("age", "30")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "contains - type mismatch boolean vs string returns false",
			data:       completeData,
			expression: `contains("metadata.isActive", "true")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "contains - empty string in field",
			data:       completeData,
			expression: `contains("name", "")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "contains - case sensitive no match",
			data:       completeData,
			expression: `contains("name", "alice")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "contains - complex expression with AND",
			data:       completeData,
			expression: `contains("address.city", "York") && contains("address.street", "Main")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "contains - complex expression with OR",
			data:       completeData,
			expression: `contains("address.city", "Boston") || contains("address.city", "York")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "contains - combined with equals",
			data:       completeData,
			expression: `equals("address.zip", "10001") && contains("address.city", "York")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "contains - combined with exists",
			data:       completeData,
			expression: `exists("address.city") && contains("address.city", "New")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "contains - containsAny",
			data:       completeData,
			expression: `contains("address.city", ["York", "Kentucky", "California"])`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "contains - containsAll",
			data:       completeData,
			expression: `containsAll("address.street", ["12", "M", "St"])`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "oneOf - name in literal list",
			data:       completeData,
			expression: `oneOf("name", ["Alice","Bob","Charlie"])`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "oneOf - name not in literal list",
			data:       completeData,
			expression: `oneOf("name", ["Bob","Charlie","David"])`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "oneOf - city in literal list",
			data:       completeData,
			expression: `oneOf("address.city", ["Boston","New York","Chicago"])`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "oneOf - city not in literal list",
			data:       completeData,
			expression: `oneOf("address.city", ["Boston","Chicago","Miami"])`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "oneOf - email in list",
			data:       completeData,
			expression: `oneOf("contacts.0.value", ["alice@example.com","bob@example.com"])`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "oneOf - single item list match",
			data:       completeData,
			expression: `oneOf("name", ["Alice"])`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "oneOf - single item list no match",
			data:       completeData,
			expression: `oneOf("name", ["Bob"])`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "oneOf - field doesn't exist returns false",
			data:       completeData,
			expression: `oneOf("nonexistent.field", ["value1","value2"])`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "oneOf - type mismatch number vs string returns false",
			data:       completeData,
			expression: `oneOf("age", ["30","40","50"])`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "oneOf - type mismatch boolean vs string returns false",
			data:       completeData,
			expression: `oneOf("metadata.isActive", ["true","false"])`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "oneOf - case sensitive no match",
			data:       completeData,
			expression: `oneOf("name", ["alice","bob","charlie"])`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "oneOf - field in literal list integers",
			data:       completeData,
			expression: `oneOf("age", [30, 40, 50])`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "oneOf - field in literal list floats",
			data:       completeData,
			expression: `oneOf("score", [30.0, 40.0, 50.0, 90.5])`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "startsWith - name starts with prefix",
			data:       completeData,
			expression: `startsWith("name", "Ali")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "startsWith - name starts with full name",
			data:       completeData,
			expression: `startsWith("name", "Alice")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "startsWith - name does not start with prefix",
			data:       completeData,
			expression: `startsWith("name", "Bob")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "startsWith - city starts with prefix",
			data:       completeData,
			expression: `startsWith("address.city", "New")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "startsWith - city does not start with prefix",
			data:       completeData,
			expression: `startsWith("address.city", "York")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "startsWith - street starts with number",
			data:       completeData,
			expression: `startsWith("address.street", "123")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "startsWith - street does not start with word",
			data:       completeData,
			expression: `startsWith("address.street", "Main")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "startsWith - email starts with username",
			data:       completeData,
			expression: `startsWith("contacts.0.value", "alice")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "startsWith - email does not start with domain",
			data:       completeData,
			expression: `startsWith("contacts.0.value", "@example")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "startsWith - department starts with word",
			data:       completeData,
			expression: `startsWith("metadata.department", "Computer")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "startsWith - department does not start with word",
			data:       completeData,
			expression: `startsWith("metadata.department", "Science")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "startsWith - field doesn't exist returns false",
			data:       completeData,
			expression: `startsWith("nonexistent.field", "prefix")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "startsWith - type mismatch number vs string returns false",
			data:       completeData,
			expression: `startsWith("age", "30")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "startsWith - type mismatch boolean vs string returns false",
			data:       completeData,
			expression: `startsWith("metadata.isActive", "true")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "startsWith - empty prefix returns true",
			data:       completeData,
			expression: `startsWith("name", "")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "startsWith - case sensitive no match",
			data:       completeData,
			expression: `startsWith("name", "alice")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "startsWith - zip code starts with digits",
			data:       completeData,
			expression: `startsWith("address.zip", "100")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "startsWith - complex expression with AND",
			data:       completeData,
			expression: `startsWith("name", "Ali") && startsWith("address.city", "New")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "startsWith - complex expression with OR",
			data:       completeData,
			expression: `startsWith("name", "Bob") || startsWith("address.city", "New")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "startsWith - combined with equal",
			data:       completeData,
			expression: `equals("name", "Alice") && startsWith("address.city", "New")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "startsWith - combined with exists",
			data:       completeData,
			expression: `exists("name") && startsWith("name", "Ali")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "startsWith - with list",
			data:       completeData,
			expression: `startsWith("name", ["Ali", "Bob", "Char"])`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "endsWith - with list",
			data:       completeData,
			expression: `endsWith("name", ["ce", "ob", "le"])`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "endsWith - name ends with suffix",
			data:       completeData,
			expression: `endsWith("name", "ice")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "endsWith - name ends with full name",
			data:       completeData,
			expression: `endsWith("name", "Alice")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "endsWith - name does not end with suffix",
			data:       completeData,
			expression: `endsWith("name", "Bob")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "endsWith - city ends with suffix",
			data:       completeData,
			expression: `endsWith("address.city", "York")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "endsWith - city does not end with suffix",
			data:       completeData,
			expression: `endsWith("address.city", "New")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "endsWith - street ends with word",
			data:       completeData,
			expression: `endsWith("address.street", "St")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "endsWith - street does not end with number",
			data:       completeData,
			expression: `endsWith("address.street", "123")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "endsWith - email ends with domain",
			data:       completeData,
			expression: `endsWith("contacts.0.value", "@example.com")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "endsWith - email ends with extension",
			data:       completeData,
			expression: `endsWith("contacts.0.value", ".com")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "endsWith - email does not end with username",
			data:       completeData,
			expression: `endsWith("contacts.0.value", "alice")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "endsWith - department ends with word",
			data:       completeData,
			expression: `endsWith("metadata.department", "Science")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "endsWith - department does not end with word",
			data:       completeData,
			expression: `endsWith("metadata.department", "Computer")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "endsWith - field doesn't exist returns false",
			data:       completeData,
			expression: `endsWith("nonexistent.field", "suffix")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "endsWith - type mismatch number vs string returns false",
			data:       completeData,
			expression: `endsWith("age", "30")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "endsWith - type mismatch boolean vs string returns false",
			data:       completeData,
			expression: `endsWith("metadata.isActive", "true")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "endsWith - empty suffix returns true",
			data:       completeData,
			expression: `endsWith("name", "")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "endsWith - case sensitive no match",
			data:       completeData,
			expression: `endsWith("name", "ALICE")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "endsWith - zip code ends with digits",
			data:       completeData,
			expression: `endsWith("address.zip", "001")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "endsWith - complex expression with AND",
			data:       completeData,
			expression: `endsWith("name", "ice") && endsWith("address.city", "York")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "endsWith - complex expression with OR",
			data:       completeData,
			expression: `endsWith("name", "Bob") || endsWith("address.city", "York")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "endsWith - combined with equal",
			data:       completeData,
			expression: `equals("name", "Alice") && endsWith("address.city", "York")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "endsWith - combined with exists",
			data:       completeData,
			expression: `exists("name") && endsWith("name", "ice")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "regexMatch- name matches simple pattern",
			data:       completeData,
			expression: `regexMatch("name", "^Alice$")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "regexMatch- name matches partial pattern",
			data:       completeData,
			expression: `regexMatch("name", "Ali")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "regexMatch- name does not match pattern",
			data:       completeData,
			expression: `regexMatch("name", "^Bob$")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "regexMatch- email matches email pattern",
			data:       completeData,
			expression: `regexMatch("contacts.0.value", "^[a-z]+@[a-z]+\\.[a-z]+$")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "regexMatch- city matches pattern with spaces",
			data:       completeData,
			expression: `regexMatch("address.city", "New.*")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "regexMatch- street matches number pattern",
			data:       completeData,
			expression: `regexMatch("address.street", "^\\d+")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "regexMatch- zip code matches 5 digits",
			data:       completeData,
			expression: `regexMatch("address.zip", "^\\d{5}$")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "regexMatch- name matches case insensitive",
			data:       completeData,
			expression: `regexMatch("name", "(?i)alice")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "regexMatch- name matches start anchor",
			data:       completeData,
			expression: `regexMatch("name", "^A")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "regexMatch- name matches end anchor",
			data:       completeData,
			expression: `regexMatch("name", "e$")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "regexMatch- department matches word boundary",
			data:       completeData,
			expression: `regexMatch("metadata.department", "\\bComputer\\b")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "regexMatch- field doesn't exist returns false",
			data:       completeData,
			expression: `regexMatch("nonexistent.field", ".*")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "regexMatch- type mismatch number vs string returns false",
			data:       completeData,
			expression: `regexMatch("age", "\\d+")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "regexMatch- type mismatch boolean vs string returns false",
			data:       completeData,
			expression: `regexMatch("metadata.isActive", "true")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "regexMatch- invalid regex returns false",
			data:       completeData,
			expression: `regexMatch("name", "[")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "regexMatch- matches any character",
			data:       completeData,
			expression: `regexMatch("name", ".")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "regexMatch- matches alternation",
			data:       completeData,
			expression: `regexMatch("name", "Alice|Bob|Charlie")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "regexMatch- complex expression with AND",
			data:       completeData,
			expression: `regexMatch("name", "^A") && regexMatch("address.city", "York$")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "regexMatch- complex expression with OR",
			data:       completeData,
			expression: `regexMatch("name", "^Bob") || regexMatch("name", "^Alice")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "regexMatch- combined with equal",
			data:       completeData,
			expression: `equals("name", "Alice") && regexMatch("address.zip", "^\\d{5}$")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "regexMatch - combined with exists",
			data:       completeData,
			expression: `exists("name") && regexMatch("name", "^[A-Z]")`,
			want:       true,
			expectErr:  false,
		},

		{
			name:       "lessThan - age less than 40",
			data:       completeData,
			expression: `lessThan("age", "40")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessThan - age less than 30 (equal case returns false)",
			data:       completeData,
			expression: `lessThan("age", "30")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessThan - age less than 20",
			data:       completeData,
			expression: `lessThan("age", "20")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessThan - score less than 100",
			data:       completeData,
			expression: `lessThan("score", "100")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessThan - score less than 90.5 (equal case returns false)",
			data:       completeData,
			expression: `lessThan("score", "90.5")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessThan - score less than 50",
			data:       completeData,
			expression: `lessThan("score", "50")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessThan - yearJoined less than 2025",
			data:       completeData,
			expression: `lessThan("metadata.yearJoined", "2025")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessThan - yearJoined less than 2020 (equal case returns false)",
			data:       completeData,
			expression: `lessThan("metadata.yearJoined", "2020")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessThan - yearJoined less than 2010",
			data:       completeData,
			expression: `lessThan("metadata.yearJoined", "2010")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessThan - avgGrade less than 90",
			data:       completeData,
			expression: `lessThan("metadata.avgGrade", "90")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessThan - avgGrade less than 80",
			data:       completeData,
			expression: `lessThan("metadata.avgGrade", "80")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessThan - field doesn't exist returns false",
			data:       completeData,
			expression: `lessThan("nonExistent", "100")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessThan - type mismatch string vs number returns false",
			data:       completeData,
			expression: `lessThan("name", "100")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessThan - type mismatch boolean vs number returns false",
			data:       completeData,
			expression: `lessThan("metadata.isActive", "100")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessThan - invalid literal value returns false",
			data:       completeData,
			expression: `lessThan("age", "not_a_number")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessThan - negative numbers comparison",
			data:       completeData,
			expression: `lessThan("age", "-10")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessThan - decimal comparison",
			data:       completeData,
			expression: `lessThan("score", "90.6")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessThan - complex expression with AND",
			data:       completeData,
			expression: `lessThan("age", "40") && lessThan("score", "100")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessThan - complex expression with OR",
			data:       completeData,
			expression: `lessThan("age", "20") || lessThan("score", "100")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessThan - combined with equal",
			data:       completeData,
			expression: `equals("name", "Alice") && lessThan("age", "50")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessThan - combined with exists",
			data:       completeData,
			expression: `exists("age") && lessThan("age", "35")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterThan - age greater than 20",
			data:       completeData,
			expression: `greaterThan("age", "20")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterThan - age greater than 30 (equal case returns false)",
			data:       completeData,
			expression: `greaterThan("age", "30")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterThan - age greater than 40",
			data:       completeData,
			expression: `greaterThan("age", "40")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterThan - score greater than 80",
			data:       completeData,
			expression: `greaterThan("score", "80")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterThan - score greater than 90.5 (equal case returns false)",
			data:       completeData,
			expression: `greaterThan("score", "90.5")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterThan - score greater than 100",
			data:       completeData,
			expression: `greaterThan("score", "100")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterThan - yearJoined greater than 2015",
			data:       completeData,
			expression: `greaterThan("metadata.yearJoined", "2015")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterThan - yearJoined greater than 2020 (equal case returns false)",
			data:       completeData,
			expression: `greaterThan("metadata.yearJoined", "2020")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterThan - yearJoined greater than 2025",
			data:       completeData,
			expression: `greaterThan("metadata.yearJoined", "2025")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterThan - avgGrade greater than 80",
			data:       completeData,
			expression: `greaterThan("metadata.avgGrade", "80")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterThan - avgGrade greater than 90",
			data:       completeData,
			expression: `greaterThan("metadata.avgGrade", "90")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterThan - field doesn't exist returns false",
			data:       completeData,
			expression: `greaterThan("nonExistent", "100")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterThan - type mismatch string vs number returns false",
			data:       completeData,
			expression: `greaterThan("name", "100")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterThan - type mismatch boolean vs number returns false",
			data:       completeData,
			expression: `greaterThan("metadata.isActive", "100")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterThan - invalid literal value returns false",
			data:       completeData,
			expression: `greaterThan("age", "not_a_number")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterThan - negative numbers comparison",
			data:       completeData,
			expression: `greaterThan("age", "-10")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterThan - decimal comparison",
			data:       completeData,
			expression: `greaterThan("score", "90.4")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterThan - complex expression with AND",
			data:       completeData,
			expression: `greaterThan("age", "20") && greaterThan("score", "80")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterThan - complex expression with OR",
			data:       completeData,
			expression: `greaterThan("age", "40") || greaterThan("score", "80")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterThan - combined with equal",
			data:       completeData,
			expression: `equals("name", "Alice") && greaterThan("age", "25")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterThan - combined with exists",
			data:       completeData,
			expression: `exists("age") && greaterThan("age", "25")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - age less or equal than 40",
			data:       completeData,
			expression: `lessOrEqual("age", "40")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - age less or equal than 30 (equal case returns true)",
			data:       completeData,
			expression: `lessOrEqual("age", "30")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - age less or equal than 20",
			data:       completeData,
			expression: `lessOrEqual("age", "20")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - score less or equal than 100",
			data:       completeData,
			expression: `lessOrEqual("score", "100")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - score less or equal than 90.5 (equal case returns true)",
			data:       completeData,
			expression: `lessOrEqual("score", "90.5")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - score less or equal than 50",
			data:       completeData,
			expression: `lessOrEqual("score", "50")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - yearJoined less or equal than 2025",
			data:       completeData,
			expression: `lessOrEqual("metadata.yearJoined", "2025")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - yearJoined less or equal than 2020 (equal case returns true)",
			data:       completeData,
			expression: `lessOrEqual("metadata.yearJoined", "2020")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - yearJoined less or equal than 2010",
			data:       completeData,
			expression: `lessOrEqual("metadata.yearJoined", "2010")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - avgGrade less or equal than 90",
			data:       completeData,
			expression: `lessOrEqual("metadata.avgGrade", "90")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - avgGrade less or equal than 85.5 (equal case returns true)",
			data:       completeData,
			expression: `lessOrEqual("metadata.avgGrade", "85.5")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - avgGrade less or equal than 80",
			data:       completeData,
			expression: `lessOrEqual("metadata.avgGrade", "80")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - field doesn't exist returns false",
			data:       completeData,
			expression: `lessOrEqual("nonExistent", "100")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - type mismatch string vs number returns false",
			data:       completeData,
			expression: `lessOrEqual("name", "100")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - type mismatch boolean vs number returns false",
			data:       completeData,
			expression: `lessOrEqual("metadata.isActive", "100")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - invalid literal value returns false",
			data:       completeData,
			expression: `lessOrEqual("age", "not_a_number")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - negative numbers comparison",
			data:       completeData,
			expression: `lessOrEqual("age", "-10")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - decimal comparison less than",
			data:       completeData,
			expression: `lessOrEqual("score", "90.6")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - decimal comparison equal",
			data:       completeData,
			expression: `lessOrEqual("metadata.avgGrade", "85.5")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - complex expression with AND",
			data:       completeData,
			expression: `lessOrEqual("age", "30") && lessOrEqual("score", "90.5")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - complex expression with OR",
			data:       completeData,
			expression: `lessOrEqual("age", "20") || lessOrEqual("score", "100")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - combined with equal",
			data:       completeData,
			expression: `equals("name", "Alice") && lessOrEqual("age", "30")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "lessOrEqual - combined with exists",
			data:       completeData,
			expression: `exists("age") && lessOrEqual("age", "35")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - age greater or equal than 20",
			data:       completeData,
			expression: `greaterOrEqual("age", "20")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - age greater or equal than 30 (equal case returns true)",
			data:       completeData,
			expression: `greaterOrEqual("age", "30")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - age greater or equal than 40",
			data:       completeData,
			expression: `greaterOrEqual("age", "40")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - score greater or equal than 80",
			data:       completeData,
			expression: `greaterOrEqual("score", "80")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - score greater or equal than 90.5 (equal case returns true)",
			data:       completeData,
			expression: `greaterOrEqual("score", "90.5")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - score greater or equal than 100",
			data:       completeData,
			expression: `greaterOrEqual("score", "100")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - yearJoined greater or equal than 2015",
			data:       completeData,
			expression: `greaterOrEqual("metadata.yearJoined", "2015")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - yearJoined greater or equal than 2020 (equal case returns true)",
			data:       completeData,
			expression: `greaterOrEqual("metadata.yearJoined", "2020")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - yearJoined greater or equal than 2025",
			data:       completeData,
			expression: `greaterOrEqual("metadata.yearJoined", "2025")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - avgGrade greater or equal than 80",
			data:       completeData,
			expression: `greaterOrEqual("metadata.avgGrade", "80")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - avgGrade greater or equal than 85.5 (equal case returns true)",
			data:       completeData,
			expression: `greaterOrEqual("metadata.avgGrade", "85.5")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - avgGrade greater or equal than 90",
			data:       completeData,
			expression: `greaterOrEqual("metadata.avgGrade", "90")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - field doesn't exist returns false",
			data:       completeData,
			expression: `greaterOrEqual("nonExistent", "100")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - type mismatch string vs number returns false",
			data:       completeData,
			expression: `greaterOrEqual("name", "100")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - type mismatch boolean vs number returns false",
			data:       completeData,
			expression: `greaterOrEqual("metadata.isActive", "100")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - invalid literal value returns false",
			data:       completeData,
			expression: `greaterOrEqual("age", "not_a_number")`,
			want:       false,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - negative numbers comparison",
			data:       completeData,
			expression: `greaterOrEqual("age", "-10")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - decimal comparison greater than",
			data:       completeData,
			expression: `greaterOrEqual("score", "90.4")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - decimal comparison equal",
			data:       completeData,
			expression: `greaterOrEqual("metadata.avgGrade", "85.5")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - complex expression with AND",
			data:       completeData,
			expression: `greaterOrEqual("age", "30") && greaterOrEqual("score", "90.5")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - complex expression with OR",
			data:       completeData,
			expression: `greaterOrEqual("age", "40") || greaterOrEqual("score", "80")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - combined with equal",
			data:       completeData,
			expression: `equals("name", "Alice") && greaterOrEqual("age", "30")`,
			want:       true,
			expectErr:  false,
		},
		{
			name:       "greaterOrEqual - combined with exists",
			data:       completeData,
			expression: `exists("age") && greaterOrEqual("age", "25")`,
			want:       true,
			expectErr:  false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			strData := ""
			if tt.data != nil {
				data, err := json.Marshal(tt.data)
				assert.NoError(t, err)
				strData = string(data)
			}
			got, err := cCache.Evaluate(&strData, tt.expression)
			if tt.expectErr {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
				assert.Equal(t, tt.want, got)
			}
		})
	}
}
